'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Inventory.WebForms

    Partial Public Class Home

        '''<summary>
        '''totalCategoriesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalCategoriesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''totalProductsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalProductsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''totalCustomersLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalCustomersLabel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
